/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ContainerStatePausedApplyConfiguration represents an declarative configuration of the ContainerStatePaused type for use
// with apply.
type ContainerStatePausedApplyConfiguration struct {
	PausedAt *v1.Time `json:"pausedAt,omitempty"`
}

// ContainerStatePausedApplyConfiguration constructs an declarative configuration of the ContainerStatePaused type for use with
// apply.
func ContainerStatePaused() *ContainerStatePausedApplyConfiguration {
	return &ContainerStatePausedApplyConfiguration{}
}

// WithPausedAt sets the PausedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PausedAt field is set to the value of the last call.
func (b *ContainerStatePausedApplyConfiguration) WithPausedAt(value v1.Time) *ContainerStatePausedApplyConfiguration {
	b.PausedAt = &value
	return b
}
